### ISSUE TITLE
When i run SympyGamma project on server , my server will crashed within some time

### ISSUE THREAD

**Issue by radhika2vasundhara** [sympy/sympy_gamma#123]

**Comment by lidavidm** [comment]
@radhika2vasundhara please provide a stack trace.

**Comment by radhika2vasundhara** [comment]
I can't get stack trace .

**Comment by radhika2vasundhara** [comment]
**Error :**
the runtime process for the instance running on port 46765 has unexpectedly quit
ERROR 2019-11-28 05:52:48,879 base.py:209] Internal Server Error: /input/
Traceback (most recent call last):
File "/var/www/html/sym_math/google_appengine/lib/django-1.3/django/core/handlers/base.py", line 178, in get_response
response = middleware_method(request, response)
File "/var/www/html/sym_math/google_appengine/lib/django-1.3/django/middleware/common.py", line 94, in process_response
if response.status_code == 404:
AttributeError: 'tuple' object has no attribute 'status_code'
ERROR 2019-11-28 14:25:50,789 base.py:209] Internal Server Error: /input/
Traceback (most recent call last):
File "/var/www/html/sym_math/google_appengine/lib/django-1.3/django/core/handlers/base.py", line 178, in get_response
response = middleware_method(request, response)
File "/var/www/html/sym_math/google_appengine/lib/django-1.3/django/middleware/common.py", line 94, in process_response
if response.status_code == 404:
AttributeError: 'tuple' object has no attribute 'status_code'
