### ISSUE TITLE
Newer Versions of NumPy need to be made supported in SymPy Gamma

### ISSUE THREAD

**Issue by ashutoshsaboo** [sympy/sympy_gamma#77]
Currently SymPy Gamma, supports the `1.6.1` version of NumPy - listed in `app.yaml` file. 

The latest available version of NumPy as of today, i.e, 18th March'16, is `1.10.4`.

Now, if we update NumPy to the latest version, 

And then after rebuilding the `app.yaml` file -:

i) if in `app.yaml` file , we change the numpy version to the latest one, then the following error pops up n the terminal while starting the Google App Engine-:

```
(sympygamma) ashutoshsaboo@ASHUTOSH-PC:~/sympy_gamma$ ../Downloads/google_appengine/dev_appserver.py .
Traceback (most recent call last):
  File "../Downloads/google_appengine/dev_appserver.py", line 83, in <module>
    _run_file(__file__, globals())
  File "../Downloads/google_appengine/dev_appserver.py", line 79, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/home/ashutoshsaboo/Downloads/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 1040, in <module>
    main()
  File "/home/ashutoshsaboo/Downloads/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 1033, in main
    dev_server.start(options)
  File "/home/ashutoshsaboo/Downloads/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 758, in start
    options.config_paths, options.app_id)
  File "/home/ashutoshsaboo/Downloads/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 831, in __init__
    module_configuration = ModuleConfiguration(config_path, app_id)
  File "/home/ashutoshsaboo/Downloads/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 127, in __init__
    self._config_path)
  File "/home/ashutoshsaboo/Downloads/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 424, in _parse_configuration
    config, files = appinfo_includes.ParseAndReturnIncludePaths(f)
  File "/home/ashutoshsaboo/Downloads/google_appengine/google/appengine/api/appinfo_includes.py", line 82, in ParseAndReturnIncludePaths
    appyaml = appinfo.LoadSingleAppInfo(appinfo_file)
  File "/home/ashutoshsaboo/Downloads/google_appengine/google/appengine/api/appinfo.py", line 2190, in LoadSingleAppInfo
    listener.Parse(app_info)
  File "/home/ashutoshsaboo/Downloads/google_appengine/google/appengine/api/yaml_listener.py", line 227, in Parse
    self._HandleEvents(self._GenerateEventParameters(stream, loader_class))
  File "/home/ashutoshsaboo/Downloads/google_appengine/google/appengine/api/yaml_listener.py", line 178, in _HandleEvents
    raise yaml_errors.EventError(e, event_object)
google.appengine.api.yaml_errors.EventError: numpy version "1.10.4" is not supported, use one of: "1.6.1"
  in "./app.yaml", line 28, column 1

```

ii) Or else, in case if we don't edit the `app.yaml` file after rebuilding it, then error #70 pops up.

I guess, we must ensure that the SymPy Gamma supports the latest version of NumPy, since as newer versions of NumPy come up, it may start deprecating previous functions, then it may cause problems with our code.

**Comment by lidavidm** [comment]
Unfortunately, you have to keep in mind that Google App Engine only supports certain versions of libraries: https://cloud.google.com/appengine/docs/python/tools/libraries27

That's why we're so behind on Django and NumPy - App Engine doesn't support them. Also, in the case of NumPy, we cannot use our own version, because it contains native code.

The fact that Google hasn't updated these libraries either, since the last time I looked at this in 2013 or 2014 or so, means that maybe they've abandoned App Engine as a platform, or at least aren't focusing on it so much.

**Comment by ashutoshsaboo** [comment]
Ohh I see @lidavidm . Then I guess, I must close this issue. Since, Google App Engine itself doesn't support it.
